#!/bin/sh

set -e
rm -rf /tmp/inferium
npm run build --prefix extras/ts-reader
node ./extras/ts-reader $1

sbt -Dsbt.log.noformat=true "cli/run /tmp/inferium/node_modules/$1 /tmp/inferium/result.json"
